version: '3.8'

services:
  online-editor:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspaces:/tmp/online-editor/workspaces
      - ./images:/tmp/online-editor/images
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
    networks:
      - editor-network

networks:
  editor-network:
    driver: bridge 